### ISSUE TITLE
Matches endpoint

### ISSUE THREAD

**Issue by roy7** [leela-zero/leela-zero-server#146]
@amj requested an endpoint to see more match history. Maybe add a link from the Test Matches title to see all of them?

**Comment by bood** [comment]
Is he doing some kind of script analysis?

We can make it a separate API returns JSON if necessary, and those web pages can call this API instead of passing by pug render engine too.

Ideally, all data can be passed in this way, it's my preferred method of getting data too. I just don't see the necessarily for this kind of change for now so I don't bother changing it.

**Comment by roy7** [comment]
I've added an endpoint at http://zero.sjeng.org/matches-all. It's slow so please only use it when needed and don't scrape it or something.

This uses the full web site layout on the results, we could also add an API style version to provide raw data too but I'll leave that to a future contributor.

**Comment by roy7** [comment]
Turned out to be way easier than I realized since we already had a pug view and an appropriate helper function in place. Sorry for the delay. :(
